### ISSUE TITLE
Roadmap link is broken

### ISSUE THREAD

**Issue by JoaoGFarias** [hcoles/pitest-site#103]
The on the [Development page](https://github.com/hcoles/pitest-site/blob/gh-pages/pages/how_to_help.markdown#development), the following link is broken:

https://github.com/hcoles/pitest-site/blob/gh-pages/roadmap

**Comment by StefanPenndorf** [comment]
Hi Joao,

the link isn't broken. You didn't browser the correct pages. Pitest's Documentation is served via github pages and is accessible at https://pitest.org

If you visit the development page at https://pitest.org/how_to_help/ the link to the roadmap - https://pitest.org/roadmap/ - works as expected. The repo pages here at the github site repo are only the sources. Thus links might not work.
