### ISSUE TITLE
Migrate to jekyll

### ISSUE THREAD

**Issue by gvsmirnov** [hcoles/pitest-site#2]
(continuing from https://github.com/hcoles/pitest/issues/122)

Hosting the site at github pages allows for instant updates to the code. I have started the migration here: https://github.com/gvsmirnov/pitest-site (the branch is `gh-pages`). To run it locally, execute `jekyll serve` (see http://jekyllrb.com/ for installation).

It is almost complete. The links are identical to the ones the site currently has. The formatting is proper in most places. The only two things that I know do not work are cross-links for footnotes and anchors. These should not be hard to fix, but I am afraid I will not have a lot of time for that this week.

**Comment by hcoles** [comment]
Looks good - I'm not clear on how the clean urls are setup, but they seem to work nicely. Thanks.

If you can get the cross links working this would definitely be an improvement over the hakyll workflow.

**Comment by gvsmirnov** [comment]
Fixed the footnotes and some other small things, also upgraded to bootstrap 3. I have checked everything, but having a fresh pair of eyes look over it should be useful as well.

**Comment by hcoles** [comment]
Managed to give it a quick once over - it looks good, although I prefer the plain white background the site currently has. 

I'll look into getting the pages repo + dns update as soon as I get chance . . . which won't be this week.

**Comment by gvsmirnov** [comment]
Fixed the background color and tweaked the navbar a little.

Here is a comprehensive [documentation](https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages) for Pages. The easiest way to go about it is creating a user/organisation page. To save you some time, I list below the quick steps to get things working.

If you create a repo `hcoles.github.io` and put the contents of https://github.com/gvsmirnov/pitest-site/tree/gh-pages to the `master` branch of it, you will only require to alter the DNS in one of the following ways:

---

**First option**: Make `A` records that point from `pitest.org` to `192.30.252.153` and `192.30.252.154`. Dig should output something like that:

``` (bash)
$ dig pitest.org +nostats +nocomments +nocmd
pitest.org.   73  IN  A 192.30.252.153
pitest.org.   73  IN  A 192.30.252.154
```

**Second option**: Make an `ALIAS` record that points from `pitest.org` to `hcoles.github.io`. Few DNS providers support this, though. If you succeed, dig should output something like that:

``` (bash)
$ dig pitest.org +nostats +nocomments +nocmd
pitest.org.   3600    IN A     199.27.73.133
```

---

Also, I see that `www.pitest.org` currently points to `pit.nfshost.com.`:

``` (bash)
$ dig www.pitest.org +nostats +nocomments +nocmd
www.pitest.org.     3578    IN  CNAME   pit.nfshost.com.
```

I believe thins should be fixed so that `www.pitest.org` is a `CNAME` for `pitest.org`

One more thing to consider is creating a separate organisation for pitest. This way, you can have a separate personal homepage :)

**Comment by hcoles** [comment]
pitest.org is now being served form the gh-pages branch of the existing pitest-site repo.

Thanks for all your work.

Henry

**Comment by gvsmirnov** [comment]
Cool! Glad to be of help.
