### ISSUE TITLE
Site may break on May 1st

### ISSUE THREAD

**Issue by hcoles** [hcoles/pitest-site#26]
It looks like some changes might be needed due to this

https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

**Comment by StefanPenndorf** [comment]
Had a short look at this issue and came to the same solution you've already pushed in 4e4f5837898bec4a00b02a39f106ef6fb5c9b78f

Couldn't find any problems with the site on a first short look. You should re-think where you want't to announce releases -- news section hasn't been updates after 1.1.4 -- but that's worth another issue, I think.

I guess this issue can be closed now.
