### ISSUE TITLE
Remove news section from pitest site

### ISSUE THREAD

**Issue by StefanPenndorf** [hcoles/pitest-site#28]
The news section isn't maintained anymore. It might be too much work to update release information on multiple places.

New releases should be
- maintained on github (pitest main project)
- announced via mailing list

Thus the news section on the page can be removed. Any thoughts on that? Maybe the [github releases page](https://github.com/hcoles/pitest/releases) should be linked somewhere.

**Comment by hcoles** [comment]
The whole site could do with a bit of a cleanup and re-design, but yes, the news section should be the first thing to go.

**Comment by hcoles** [comment]
News section removed.
