### ISSUE TITLE
Site not updating

### ISSUE THREAD

**Issue by hcoles** [hcoles/pitest-site#5]
The jekyll build is completing successfully, but updates to the site are not appearing at http://pitest.org.

Each push results in an e-mail stating

> The page build completed successfully, but returned the following warning:
> 
> CNAME already taken: pitest.org

Could it be that the site is being served from @gvsmirnov fork as that was the first repo to contain the cname file?

**Comment by hcoles** [comment]
All fixed with help from github support.

**Comment by gvsmirnov** [comment]
What was the issue?

**Comment by hcoles** [comment]
@gvsmirnov As I'd guessed the site was being served from your fork.

**Comment by gvsmirnov** [comment]
Ah. Removed the fork just in case this issue might resurface.
