### ISSUE TITLE
What should we do about the "new" site ?

### ISSUE THREAD

**Issue by maxgabut** [hcoles/pitest-site#64]
I noticed that the site sources contains a `new.html` file as well as a `css/new/pit.css` file. The result is currently visible at [pitest.org/new.html](http://pitest.org/new.html).

It has been there for almost 2 years now.

Is there plans to apply this style to the rest of the site ?
If not, I think we should remove it from the sources.

**Comment by hcoles** [comment]
It would be good to update the site as it's looking more than a little dated. I'm not sure my playing about with vivus is necessarily an improvement though, so happy for it to go.
