### ISSUE TITLE
Enable https on pitest.org

### ISSUE THREAD

**Issue by maxgabut** [hcoles/pitest-site#67]
It is now possible to use https for github pages. It is the default for new sites, but it has to be enabled for sites created before June 15, 2016.

It seems quite simple to [enable https](https://help.github.com/articles/securing-your-github-pages-site-with-https/). I think it would be good to have it.

**Comment by maxgabut** [comment]
@hcoles what do you think of this idea ?

**Comment by hcoles** [comment]
@maxgabut yes, excellent idea - now finally implemented. Thanks for the suggestion.
