### ISSUE TITLE
--maxMutationsPerClass description is bogus

### ISSUE THREAD

**Issue by Vampire** [hcoles/pitest-site#93]
It says: `The maximum number of mutations to create per class. Use 0 or -ve number to set no limit.`
I don't think `-ve` is intentional there.

**Comment by StefanPenndorf** [comment]
While trying to find out what can and should fit in there I couldn't retrace the data flow to the `LimitNumberOfMutationsPerClassFilterFactory` - that said it seems to me the parameter is currently unused. Maybe I'm missing something. 

I found this description in OptionsParser:
> No longer supported. Use CLASSLIMIT(limit[42]) feature instead

Thus there might be a bigger update needed removing the parameter and adding Feature/Plugin descriptions. I couldn't find any documentation about feature parameters and default features/plugins.

**Comment by hcoles** [comment]
Finally updated the docs for now defunct parameters such as this one.
